YTeAspMVC/Models/Advise.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace YTeAspMVC.Models
{
    public class Advise
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdAdvise { get; set; }

        [Required]
        public string FullName { get; set; }

        [Required]
        public string Email { get; set; }

        public string Question { get; set; }

        public string Created { get; set; }

    }
}

YTeAspMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YTeAspMVC.Daos;
using YTeAspMVC.Models;

namespace YTeAspMVC.Controllers
{
    public class HomeController : Controller
    {
        DoctorDao doctorDao = new DoctorDao();
        ServiceDao serviceDao = new ServiceDao();
        PostDao postDao = new PostDao();
        public ActionResult Index(string mess)
        {
            ViewBag.Doctor = doctorDao.GetTop3();
            ViewBag.Service = serviceDao.GetTop3();
            ViewBag.Post = postDao.GetTop3();
            ViewBag.Msg = mess;
            return View();
        }

        public ActionResult Advise()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Advise(Advise advise)
        {

            advise.Created = DateTime.Now.ToString();
            postDao.AddAdvise(advise);
            ViewBag.Msg = "1";
            return View("Advise");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

YTeAspMVC/Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace YTeAspMVC.Controllers
{
    public class ModulesController : Controller
    {
        // GET: PublicModules
        [ChildActionOnly]
        public ActionResult Header()
        {
            return PartialView();
        }

        [ChildActionOnly]
        public ActionResult Footer()
        {
            return PartialView();
        }

        [ChildActionOnly]
        public ActionResult NavigationBar()
        {
            return PartialView();
        }

        [ChildActionOnly]
        public ActionResult MainSlider()
        {
            return PartialView();
        }
        
    }
}

YTeAspMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

YTeAspMVC/Views/Home/Advise.cshtml
@{
    ViewBag.Title = "Advise";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ var userInfomatiom = (YTeAspMVC.Models.User)Session["USER"]; }
<section class="breadcrumb-area" style="background-image: url(/Content/images/resources/breadcrumb-bg.jpg);">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="inner-content clearfix">
                    <div class="title float-left">
                        <h2>Tư vấn</h2>
                    </div>
                    <div class="breadcrumb-menu float-right">
                        <ul class="clearfix">
                            <li><a href="/Home/Index">Home</a></li>
                            <li><i class="fa fa-angle-right" aria-hidden="true"></i></li>
                            <li class="active">Tư vấn</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@if (ViewBag.Msg == "1")
{
    <div class="toast" data-delay="1000" style="position:fixed; top: 100PX; left: 40PX;z-index: 2000;width: 300px">
        <script>
            swal({
                title: 'Gửi câu hỏi thành công!',
                /* text: 'Redirecting...', */
                icon: 'success',
                timer: 3000,
                buttons: true,
                type: 'success'
            })
        </script>
    </div>
}
<!--End breadcrumb area-->
<!--Start Contact info map area-->
<!--End Contact info map area-->
<!--Start contact form area-->
<section class="contact-form-area">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <div class="contact-form">
                    @if (userInfomatiom != null)
                    {
                        <form name="contact_form" class="default-form" action="/Home/Advise" method="post">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-box">
                                        <input type="text" class="form-control" name="FullName" value="@userInfomatiom.FullName" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-box">
                                        <input type="email" class="form-control" name="Email" value="@userInfomatiom.Email" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input-box">
                                        <textarea class="form-control" name="Question" placeholder="Nội dung câu hỏi" required></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="button-box">
                                        <button class="btn-one" type="submit">Gửi câu hỏi</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    }
                    else
                    {
                        <form name="contact_form" class="default-form" action="/Home/Advise" method="post">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-box">
                                        <input type="text" class="form-control" name="FullName" placeholder="Họ tên" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-box">
                                        <input type="email" class="form-control" name="Email" placeholder="Email" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input-box">
                                        <textarea class="form-control" name="Question" placeholder="Nội dung câu hỏi" required></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="button-box">
                                        <button class="btn-one" type="submit">Gửi câu hỏi</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

YTeAspMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

YTeAspMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@Html.Action("MainSlider", "Modules")
    <section class="welcome-area sec-pd1">
        @if (ViewBag.Msg != null && ViewBag.Msg == "2")
        {
            <div class="toast" data-delay="1000" style="position:fixed; top: 100PX; left: 40PX;z-index: 2000;width: 300px" >

                <script >
            swal({
                title: 'Bạn đã lấy số cho ngày hôm nay rồi!',
                /* text: 'Redirecting...', */
                icon: 'error',
                timer: 6000,
                buttons: true,
                type: 'error'
            })
                </script>
            </div>
        }
        <div class="container">
            <div class="sec-title max-width text-center">
                <h1>Phòng khám đa khoa An Tâm</h1>
                <h3>Nơi đưa đến cho bạn các dịch vụ y tế hiện tại, tin tức sức khỏe mới nhất</h3>
            </div>
            <div class="row">
                <!--Start Single Welcome Box-->
                <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12">
                    <div class="single-welcome-box text-center">
                        <div class="icon-holder">
                            <img src="~/Content/images/icon/icon-1.png" alt="Icon" style="height : 100px">
                        </div>
                        <div class="text-holder">
                            <h3>Tin tức</h3>
                            <p>Cập nhập các tin tức mới nhất về sức khỏe, các mẹo hay để chăm sóc sức khỏe.</p>
                            <a class="btn-one" href="/Post/Index">Xem thêm</a>
                        </div>
                    </div>
                </div>
                <!--End Single Welcome Box-->
                <!--Start Single Welcome Box-->
                <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12">
                    <div class="single-welcome-box text-center">
                        <div class="icon-holder">
                            <img src="~/Content/images/icon/icon-2.png" alt="Icon" style="height : 100px">
                        </div>
                        <div class="text-holder">
                            <h3>Dịch vụ</h3>
                            <p>Cung cấp các dịch hiện đại, tiện nghi, an toàn sức khỏe và dễ dàng sử dụng với mọi người.</p>
                            <a class="btn-one" href="/Service/Index">Xem thêm</a>
                        </div>
                    </div>
                </div>
                <!--End Single Welcome Box-->
                <!--Start Single Welcome Box-->
                <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12">
                    <div class="single-welcome-box text-center">
                        <div class="icon-holder">
                            <img src="~/Content/images/icon/icon-3.png" alt="Icon" style="height : 100px">
                        </div>
                        <div class="text-holder">
                            <h3>Bác sĩ</h3>
                            <p>Hội tụ các bác sĩ chuyên khoa, kĩ năng giỏi và thân thiện hòa đồng với bệnh nhân.</p>
                            <a class="btn-one" href="/Doctor/Index">Xem thêm</a>
                        </div>
                    </div>
                </div>
                <!--End Single Welcome Box-->
            </div>
        </div>
    </section>
<!--End Welcome area-->
<!--Start fact counter area-->
<section class="fact-counter-area" style="background-image: url(~/Content/images/parallax-background/fact-counter-bg.jpg);">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <ul class="clearfix">
                    <!--Start single fact counter-->
                    <li class="single-fact-counter text-center wow fadeInUp" data-wow-delay="300ms">
                        <div class="count-box">
                            <div class="icon">
                                <span class="icon-tooth-3"></span>
                            </div>
                            <h1>
                                <span class="timer" data-from="1" data-to="4257" data-speed="5000" data-refresh-interval="50">1000+</span>
                            </h1>
                            <div class="title">
                                <h3>Bệnh nhân</h3>
                            </div>
                        </div>
                    </li>
                    <!--End single fact counter-->
                    <!--Start single fact counter-->
                    <li class="single-fact-counter text-center wow fadeInUp" data-wow-delay="600ms">
                        <div class="count-box">
                            <div class="icon">
                                <span class="icon-doctor-1"></span>
                            </div>
                            <h1>
                                <span class="timer" data-from="1" data-to="18" data-speed="5000" data-refresh-interval="50">100 +</span>
                            </h1>
                            <div class="title">
                                <h3>Bác sĩ</h3>
                            </div>
                        </div>
                    </li>
                    <!--End single fact counter-->
                    <!--Start single fact counter-->
                    <li class="single-fact-counter text-center wow fadeInUp" data-wow-delay="900ms">
                        <div class="count-box">
                            <div class="icon">
                                <span class="icon-hospital"></span>
                            </div>
                            <h1>
                                <span class="timer" data-from="1" data-to="6" data-speed="5000" data-refresh-interval="50">20 +</span>
                            </h1>
                            <div class="title">
                                <h3>Chi nhánh</h3>
                            </div>
                        </div>
                    </li>
                    <!--End single fact counter-->
                </ul>
            </div>
        </div>
    </div>
</section>
<!--End fact counter area-->
<!--Start About Area-->
<!--End services style2 area-->
<!--Start Appointment Area-->
<!--End Appointment Area-->
<!--Start team area-->
<section class="team-area">
    <div class="container">
        <div class="sec-title text-center">
            <h1>Top 3 bác sĩ </h1>
        </div>
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <div class="team-carousel owl-carousel owl-theme">
                    @foreach (var doctor in ViewBag.Doctor)
                    {
                        <!--Start single item member-->
                        <div class="single-team-member">
                            <div class="img-holder">
                                <img src="~/Content/images/@doctor.Image" alt="Awesome Image" style="height : 350px !important">
                                <div class="overlay-style-one"></div>
                                <div class="text-holder text-center">
                                    <h3>@doctor.FullName</h3>
                                    <span>@doctor.Specialist</span>
                                    <div class="button">
                                        <a class="btn-one" href="#">Đặt Lịch</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                    <!--End single item member-->
                    <!--End single item member-->
                    <!--Start single item member-->
                    <!--End single item member-->

                </div>
            </div>
        </div>
    </div>
</section>
<!--End team area-->
<!--Start Work area-->
<!--End Testimonial Sec style2-->
<!--Start Warranties sec-->
<!--End Warranties sec-->
<!--Start latest blog area-->
<section class="latest-blog-area sec-pd1 pd-btm60" style="margin-top : -150px !important">
    <div class="container inner-content">
        <div class="sec-title max-width text-center">
            <h1>Top 3 Dịch vụ y tế</h1>
        </div>
        <div class="row">
            @foreach (var service in ViewBag.Service)
            {
                <!--Start single blog post-->
                <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12">
                    <div class="single-blog-post">
                        <div class="img-holder">
                            <img src="~/Content/images/@service.Image" style="height : 250px !important" alt="Awesome Image">
                            <div class="categorie-button">
                                <a class="btn-one" href="#">Dịch vụ</a>
                            </div>
                        </div>
                        <div class="text-holder">
                            <div class="meta-box">
                                <div class="author-thumb">
                                    <img src="https://cdn2.iconfinder.com/data/icons/user-avatars-3/100/Doctor-512.png" alt="Image">
                                </div>
                                <ul class="meta-info">
                                    <li><a href="#">Đăng bởi quản trị viên</a></li>
                                    <li><a href="#">@String.Format("{0:dd-MM-yyyy}", service.Created)</a></li>
                                </ul>
                            </div>
                            <h3 class="blog-title"><a href="/Service/Detail/@service.IdService">@service.Name</a></h3>

                            <div class="readmore-button">
                                <a class="btn-two" href="/Service/Detail/@service.IdService"><span class="flaticon-next"></span>Xem thêm</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!--End single blog post-->
            }
        </div>
    </div>
</section>
<!--End latest blog area-->
<section class="latest-blog-area sec-pd1 pd-btm60" style="margin-top : -150px !important">
    <div class="container inner-content">
        <div class="sec-title max-width text-center">
            <h1>Tin tức sức khỏe mới nhất</h1>
        </div>
        <div class="row">
            @foreach (var post in ViewBag.Post)
            {
                <!--Start single blog post-->
                <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12">
                    <div class="single-blog-post">
                        <div class="img-holder">
                            <img src="~/Content/images/@post.Image" style="height : 250px !important" alt="Awesome Image">
                            <div class="categorie-button">
                                <a class="btn-one" href="#">Tin tức</a>
                            </div>
                        </div>
                        <div class="text-holder">
                            <div class="meta-box">
                                <div class="author-thumb">
                                    <img src="https://cdn2.iconfinder.com/data/icons/user-avatars-3/100/Doctor-512.png" alt="Image">
                                </div>
                                <ul class="meta-info">
                                    <li><a href="#">Đăng bởi quản trị viên</a></li>
                                    <li><a href="#">@String.Format("{0:dd-MM-yyyy}", post.Created)</a></li>
                                </ul>
                            </div>
                            <h3 class="blog-title"><a href="/Post/Detail/@post.IdPost">@post.Title</a></h3>

                            <div class="readmore-button">
                                <a class="btn-two" href="/Post/Detail/@post.IdPost"><span class="flaticon-next"></span>Xem thêm</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!--End single blog post-->
            }

        </div>
    </div>
</section>
<!--Start Brand area-->
<section class="brand-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="brand">
                    <!--Start single item-->
                    <li class="single-item">
                        <a href="#"><img src="~/Content/images/brand/1.png" alt="Awesome Brand Image"></a>
                    </li>
                    <!--End single item-->
                    <!--Start single item-->
                    <li class="single-item">
                        <a href="#"><img src="~/Content/images/brand/2.png" alt="Awesome Brand Image"></a>
                    </li>
                    <!--End single item-->
                    <!--Start single item-->
                    <li class="single-item">
                        <a href="#"><img src="~/Content/images/brand/3.png" alt="Awesome Brand Image"></a>
                    </li>
                    <!--End single item-->
                    <!--Start single item-->
                    <li class="single-item">
                        <a href="#"><img src="~/Content/images/brand/4.png" alt="Awesome Brand Image"></a>
                    </li>
                    <!--End single item-->
                </ul>
            </div>
        </div>
    </div>
</section>